definition:
  - name: ping
    filter:
      - match: "PING (.+?) "
        color: "magenta+h"
      - match: "\\d+\\.\\d+\\.\\d+\\.\\d+"
        color: "magenta"
      - match: "\\D(\\d\\.\\d\\d\\d) ?m?s?"
        color: "green"
      - match: "\\D(\\d\\d\\.\\d\\d\\d) ?m?s?"
        color: "yellow"
      - match: "\\D(\\d\\d\\d\\.\\d\\d\\d) ?m?s?"
        color: "red"
      - match: "Request timeout .+"
        color: "red+h:red"
  - name: diff
    filter:
      - match: "^(\\+.*?$)"
        color: "green+h"
      - match: "^(\\>[^\\>].*|$)"
        color: "green+h"
      - match: "^(\\-\\-\\-.+?$|$)"
        color: "red+h"
      - match: "^([\\<\\-][^\\<].*|$)"
        color: "red+h"
      - match: "^@@ .*? @@$"
        color: "cyan+h"
  - name: test
    filter:
      - match: "// TEST.+"
        color: "black+h"
      - match: "outer.*outer"
        color: "green"
      - match: "i[n\\(\\)]+er"
        color: "yellow"
      - match: "i(.{2})er"
        color: "magenta"
        disable: false
      - match: "in(\\(.\\))er"
        color: "red+h"