definition:
  - name: ping
    filter:
      - match: "viper"
        color: "yellow"
      - match: "C(\\w+)g"
        replace: "--C--${1}--G--"
        color: "magenta"
      - match: "func"
        replace: "function"
        color: "cyan"
  - name: diff
    filter:
      - match: "// TEST.+"
        color: "black+h"
      - match: "outer.*outer"
        color: "green+h"
      - match: "inner"
        color: "red+h"
      - match: "n(n)e"
        color: "white+h"