definition:
  - name: ping
    filter:
      - match: "viper"
        color: "yellow"
      - match: "C(\\w+)g"
        replace: "--C--${1}--G--"
        color: "magenta"
      - match: "func"
        replace: "function"
        color: "cyan"
  - name: test
    filter:
      - match: "// TEST.+"
        color: "black+h"
      - match: "outer.*outer"
        color: "green"
      - match: "i[n\\(\\)]+er"
        color: "yellow"
      - match: "i(nn)er"
        color: "magenta"
        disable: false
      - match: "in(\\(n\\))er"
        color: "red+h"