definition:
  - name: ping
    filter:
      - match: "\\d+\\.\\d+\\.\\d+\\.\\d+"
        color: "magenta"
      - match: "=(\\d\\.\\d\\d\\d) ms"
        color: "green"
      - match: "=(\\d\\d\\.\\d\\d\\d) ms"
        color: "yellow"
      - match: "=(\\d\\d\\d\\.\\d\\d\\d) ms"
        color: "red"
      - match: "Request timeout .+"
        color: "red+bh:red"
  - name: test
    filter:
      - match: "// TEST.+"
        color: "black+h"
      - match: "outer.*outer"
        color: "green"
      - match: "i[n\\(\\)]+er"
        color: "yellow"
      - match: "i(nn)er"
        color: "magenta"
        disable: false
      - match: "in(\\(n\\))er"
        color: "red+h"